import { Router } from 'express';
import { adminRoutes } from './admin';
import { analyticsRoutes } from './analytics.routes';
import { answerRoutes } from './answer.routes';
import { authRoutes } from './auth.routes';
import { blogRoutes } from './blog.routes';
import { categoryRoutes } from './category.routes';
import { commentRoutes } from './comment.routes';
import { healthRoutes } from './health.routes';
import { messageRoutes } from './message.routes';
import { notificationRoutes } from './notification.routes';
import { postRoutes } from './post.routes';
import { pollRoutes } from './poll.routes';
import { projectRoutes } from './project.routes';
import { questionRoutes } from './question.routes';
import { rankingRoutes } from './ranking.routes';
import { searchRoutes } from './search.routes';
import { seriesRoutes } from './series.routes';
import { snippetRoutes } from './snippet.routes';
import { settingsRoutes } from './settings.routes';
import { tagRoutes } from './tag.routes';
import { uploadRoutes } from './upload.routes';
import { userRoutes } from './user.routes';

export const apiRouter = Router();

apiRouter.use('/health', healthRoutes);
apiRouter.use('/auth', authRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/posts', postRoutes);
apiRouter.use('/blogs', blogRoutes);
apiRouter.use('/snippets', snippetRoutes);
apiRouter.use('/questions', questionRoutes);
apiRouter.use('/answers', answerRoutes);
apiRouter.use('/projects', projectRoutes);
apiRouter.use('/series', seriesRoutes);
apiRouter.use('/comments', commentRoutes);
apiRouter.use('/upload', uploadRoutes);
apiRouter.use('/messages', messageRoutes);
apiRouter.use('/notifications', notificationRoutes);
apiRouter.use('/poll', pollRoutes);
apiRouter.use('/search', searchRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/tags', tagRoutes);
apiRouter.use('/categories', categoryRoutes);
apiRouter.use('/rankings', rankingRoutes);
apiRouter.use('/analytics', analyticsRoutes);
apiRouter.use('/admin', adminRoutes);
